Dann/boj/1026 7795
GDSC-Algorithm/study pull request #5
Opened 2022-09-30 15:51 UTC by CWCTBOY

코드리뷰 부탁드려용

2022-10-02 15:15 UTC, happyjamy requested changes
열심히 하셨네요👏👍

2022-10-02 15:15 UTC, happyjamy commented on week2/BOJ_1026_박인재.py
> +A = sorted(list(map(int, input().split())))[::-1]
이거 `sorted(list(map(int, input().split())),reverse=True)` 로 안하고 왜 인덱싱 슬라이스로 했나요?

2022-10-02 15:15 UTC, happyjamy commented on week2/BOJ_7795_박인재.py
> +  A = [i for i in list(map(int, sys.stdin.readline().split()))]
이거 `[i for i in map(int, sys.stdin.readline().split())]` 이걸로 적어야 하지 않나요? list를 하고 for 문을 돌리는건 의미가 없잖아요

2022-10-04 06:41 UTC, hyeok55 commented on week2/BOJ_7795_박인재.py
> +  A = [i for i in list(map(int, sys.stdin.readline().split()))]
둘 다 iterable하면 상관 없지 않을까요?

2022-10-04 06:56 UTC, yoouung commented on week2/BOJ_7795_박인재.py
> +  count += str(a_bigger_than_b) + '\n'
왜 string타입으로 저장하셨는지 궁금해요

2022-10-04 13:25 UTC, CWCTBOY commented on week2/BOJ_7795_박인재.py
> +  A = [i for i in list(map(int, sys.stdin.readline().split()))]
이건 오타입니다.. 수정할게요

2022-10-04 13:25 UTC, CWCTBOY commented on week2/BOJ_1026_박인재.py
> +A = sorted(list(map(int, input().split())))[::-1]
제가 평소에 하는 방식으로만 하다 보니 이렇게 썼습니다!

2022-10-04 13:27 UTC, CWCTBOY commented on week2/BOJ_7795_박인재.py
> +  count += str(a_bigger_than_b) + '\n'
원래는 빈 배열에 넣어주고 마지막에 그 배열 요소들을 하나씩 꺼내 출력했는데, 그냥 아웃풋이 나올 때마다 문자열로 만들어 주고 한번에 출력하는 것이 효율적이라고 생각해 문자열로 만들었습니다!

2022-10-05 10:38 UTC, hyeok55 commented on week2/BOJ_7795_박인재.py
> +  A = [i for i in list(map(int, sys.stdin.readline().split()))]
수고하셨습니다

2022-10-05 10:39 UTC, happyjamy reviewed
긋

2022-10-05 10:40 UTC, happyjamy approved these changes

2022-10-05 10:40 UTC, merged